backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "src/content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.gf., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/EventLayout.astro"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Caption", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "ddd MMMM DD, YYYY"}
      - {label: "Image (800 x 450px) .webp", name: "image", widget: "image"}
      - {label: "Image (800 x 800px) .webp", name: "thumbnail", widget: "image"}
      - {label: "Video URL", name: "videourl", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["Heart Check"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "member" # Used in routes, e.g., /admin/collections/members
    label: "Member" # Used in the UI
    folder: "src/content/members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MemberLayout.astro"}
      - {label: "Acronym", name: "acronym", widget: "string"}
      - {label: "Full name", name: "fullname", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Website URL", name: "url", widget: "string"}
      - {label: "Logo (800 x 800 or any highres dimension)", name: "logo", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "slider" # Used in routes, e.g., /admin/collections/slider
    label: "Slider" # Used in the UI
    folder: "src/content/sliders" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/SliderLayout.astro"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Event Date", name: "date", widget: "date", date_format: "ddd MMMM DD, YYYY"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Video URL", name: "videourl", widget: "string", required: false}
      - {label: "Desktop Image (1326 x 602px)", name: "desktopimage", widget: "image"}
      - {label: "Mobile Image (768 x 349px)", name: "mobileimage", widget: "image"}
      - {label: "Slider Type", name: "type", widget: "select", options: ["Generic", "Program"]}
      - {label: "Body", name: "body", widget: "markdown", required: false}